sudo: required

env:
  matrix:
    - DOCKER_IMAGE=ubuntu:16.04
    - DOCKER_IMAGE=ubuntu:16.10

services:
  - docker

language: c++

compiler:
  - gcc

before_install:
  - echo $DOCKER_IMAGE
  - docker pull $DOCKER_IMAGE
  - docker run -d $DOCKER_IMAGE /bin/sh -C 'while true; do sleep 1; done'

before_script:
  - docker exec -it $(docker ps -aq) /bin/sh -C 'sudo apt-get -qq update'
  - docker exec -it $(docker ps -aq) /bin/sh -C 'sudo apt-get install -y sudo build-essential linux-headers-$(uname -r)'

script:
  - docker exec -it $(docker ps -aq) /bin/sh -C 'make && sudo make install'
