sudo: required

env:
  matrix:
    - DOCKER_IMAGE=ubuntu:16.04
    - DOCKER_IMAGE=ubuntu:16.10

services:
  - docker

language: c++

compiler:
  - gcc

before_install:
  - echo $DOCKER_IMAGE
  - docker pull $DOCKER_IMAGE
  - docker run -it $DOCKER_IMAGE bash

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y sudo build-essential linux-headers-$(uname -r)

script:
  - make && sudo make install
